### ISSUE TITLE
DATABASE_URL is not set.

### ISSUE THREAD

**Issue by trsteel88** [symfonycorp/platformsh-symfony-template#21]
Hi,

https://github.com/platformsh/symfonyflex-bridge has been abandoned and neither that or this repository explains how to automatically set the DATABASE_URL.

Is there a way to automate this or does this need to be manually set somewhere?

**Comment by trsteel88** [comment]
Apologies, the URL on the other repository was dead but it looks like it has just started working. I'm guessing it has only just been published.

I will read the docs and close this for now.

**Comment by fabpot** [comment]
It is setup automatically for you.
But only if you have this line in your build hook: https://github.com/symfonycorp/platformsh-symfony-template/blob/6.2/.platform.app.yaml#L47
I agree that the currents docs at https://symfony.com/doc/current/cloud/env.html are not clear about this. I will update this ASAP.

**Comment by trsteel88** [comment]
Hey @fabpot, thanks for the quick response. I already have this line but it still fails.

```
W: + symfony composer install --prefer-dist --optimize-autoloader --apcu-autoloader --classmap-authoritative --no-progress --no-ansi --no-interaction
          W: Installing dependencies from lock file
          W: Verifying lock file contents can be installed on current platform.
          W: Nothing to install, update or remove
          W: Generating optimized autoload files
          W: 81 packages you are using are looking for funding.
          W: Use the `composer fund` command to find out more!
          W: 
          W: Run composer recipes at any time to see the status of your Symfony recipes.
          W: 
          W: Executing script cache:clear [KO]
          W:  [KO]
          W: Script cache:clear returned with error code 255
          W: !!  
          W: !!  In ExceptionConverter.php line 101:
          W: !!                                                                                 
          W: !!    An exception occurred in the driver: SQLSTATE[HY000] [2002] No such file or  
          W: !!     directory                                                                   
          W: !!                                                                                 
          W: !!  
          W: !!  In Exception.php line 28:
          W: !!                                                      
          W: !!    SQLSTATE[HY000] [2002] No such file or directory  
          W: !!                                                      
          W: !!  
          W: !!  In Driver.php line 34:
          W: !!                                                      
          W: !!    SQLSTATE[HY000] [2002] No such file or directory  
          W: !!                                                      
          W: !!  
          W: !!  
          W: Script @auto-scripts was called via post-install-cmd
          W: unable to run /app/.global/bin/composer2 install --prefer-dist --optimize-autoloader --apcu-autoloader --classmap-authoritative --no-progress --no-ansi --no-interaction
        
        E: Error building project: Step failed with status code 255.

      E: Error: Unable to build application, aborting.
```
